sudo: false
language: node_js

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - for i in {1..60}; do pg_isready && break; sleep 1; done
  - psql -U postgres -c "CREATE USER test WITH PASSWORD 'dbpass'"
  - psql -U postgres -c "CREATE DATABASE test WITH OWNER test"

script:
  - make deps
  - DATABASE_URL=postgresql://test:dbpass@localhost:5432/test make test
  - make lint

node_js:
  - "8"
  - "node"
